github:
patreon: Timeraa
open_collective: premid
ko_fi: timeraa
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ZU8Q766ACS2WS&lc=US
